#!/usr/bin/env node
/**
 * init-env.mjs — cross-platform secret initialisation script.
 *
 * Generates a fresh .env file with cryptographically strong secrets.
 * Safe to re-run: will NOT overwrite an existing .env unless --force is passed.
 *
 * Usage:
 *   node scripts/init-env.mjs          # create .env (fails if it already exists)
 *   node scripts/init-env.mjs --force  # overwrite existing .env
 */

import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ROOT = resolve(__dirname, '..')
const ENV_PATH = resolve(ROOT, '.env')

const force = process.argv.includes('--force')

if (existsSync(ENV_PATH) && !force) {
  console.error(
    `\n  .env already exists at ${ENV_PATH}\n` +
      '  To overwrite it, run: node scripts/init-env.mjs --force\n',
  )
  process.exit(1)
}

/** @param {number} bytes */
function secret(bytes = 32) {
  return randomBytes(bytes).toString('hex')
}

const env = `# ──────────────────────────────────────────────────────────────────────────────
# support-llm4agents — local / self-hosted environment
# Generated by scripts/init-env.mjs on ${new Date().toISOString()}
#
# DO NOT commit this file.  Add .env to your .gitignore.
# ──────────────────────────────────────────────────────────────────────────────

# ── Database ─────────────────────────────────────────────────────────────────
DATABASE_URL=postgresql://support:support@localhost:5432/support_llm4agents

# ── Auth ─────────────────────────────────────────────────────────────────────
# JWT signing secret — 64 hex chars (256 bits)
JWT_SECRET=${secret(32)}

# Session cookie secret — 64 hex chars
SESSION_SECRET=${secret(32)}

# ── Encryption ───────────────────────────────────────────────────────────────
# AES-256 key used to encrypt the llm4agents API key at rest — 64 hex chars
ENCRYPTION_KEY=${secret(32)}

# ── LLM4Agents ───────────────────────────────────────────────────────────────
# Leave empty here; the onboarding wizard will persist it encrypted in the DB.
LLM4AGENTS_API_KEY=

# ── App ──────────────────────────────────────────────────────────────────────
NODE_ENV=development
PORT=3001
PUBLIC_URL=http://localhost:3001

# ── Admin UI ─────────────────────────────────────────────────────────────────
VITE_API_BASE_URL=http://localhost:3001/v1
`

writeFileSync(ENV_PATH, env, { encoding: 'utf8' })
console.log(`\n  .env written to ${ENV_PATH}\n`)
console.log('  Next steps:')
console.log('    1. Review/edit .env if needed.')
console.log('    2. docker compose -f docker/docker-compose.yml up -d')
console.log('    3. Open http://localhost:3000 and complete the onboarding wizard.\n')
